### PR TITLE
Continue

### PR DESCRIPTION
**Pull request by be-marc**
* Allows to pass a `c_hash` to the private `$.eval_many()` method

### CODE REVIEW

**Comment by jakob-r** [comment]
So it looks like you are changing bbotk because of something quite `mlr3tuning` specific. I would like to avoid that.
Lets see if there is an easier solution:

- Can I pass the `c_hash` within the `xxs`. At the moment it just gets lost anyway?

- A grid search that is able to *continue* is already a special grid search right? So it could be a dedicated tuner in `mlr3tuning`?

**Comment by be-marc** [comment]
Yes you are right. We should implement this without changing bbotk.

> Can I pass the c_hash within the xxs. At the moment it just gets lost anyway?

We could also overwrite `eval_many` in `ObjectiveTuning`. What do you mean with lost?

 > A grid search that is able to continue is already a special grid search right? So it could be a dedicated tuner in mlr3tuning?

Sounds good

**Comment by jakob-r** [comment]
> What do you mean with lost?

It's not actually used in `.eval_many `, isn't it?

**Comment by be-marc** [comment]
Yes it is not used in the default `.eval_many`. I copied the modified `eval_many` with `c_hash` to `ObjectiveTuning` so we do not have to change bbotk anymore.

**Pull request closed without merging**
