### PR TITLE
expect list elements are NA instead of NULL

### PR DESCRIPTION
**Pull request by tdhock**
hi @be-marc I submitted a PR to `data.table` https://github.com/Rdatatable/data.table/pull/5053 that will break one of your tests, so here is the fix to your test.

### CODE REVIEW

**Comment by jakob-r** [comment]
Are we sure we want NAs?

**Comment by be-marc** [comment]
> Are we sure we want NAs?

That's fine. The `NA`s are only set for extra columns in the archive.

We could have noticed the bug ourselves...

https://github.com/mlr-org/bbotk/blob/f1a08cdb8804a948ef029096ee6a473f16c004d7/tests/testthat/test_OptimInstanceSingleCrit.R#L64-L65


@tdhock  Thank you. We merge when the new data.table version is on CRAN.

**Comment by mllg** [comment]
@be-marc please merge this with an if-clause checking for the respective version in order to not block the data.table guys.

**Comment by tdhock** [comment]
actually before merging https://github.com/Rdatatable/data.table/pull/5053 Matt introduced a special case to avoid breaking your code so we can close for now. maybe we can re-open one day if data.table decides to expand use of NA instead of NULL.

**Pull request closed without merging**
